__package__({ name: "chatbot", short: "Sessionstream xgoja chatbot demo" })

const express = require("express")
const ss = require("sessionstream")
const pb = require("sessionstream.examples.chatdemo.v1")
const timer = require("timer")
const assets = require("fs:assets")

const sessionId = "demo"
let messageSeq = 0
let hub = null
let wsServer = null

function nextMessageId(prefix) {
  messageSeq += 1
  return `${prefix}-${messageSeq}`
}

function registerSchemas() {
  return ss.schemas()
    .registerCommand("ChatStartInference", pb.StartInferenceCommand)
    .registerEvent("ChatUserMessageAccepted", pb.UserMessageAcceptedEvent)
    .registerEvent("ChatInferenceStarted", pb.InferenceStartedEvent)
    .registerEvent("ChatTokensDelta", pb.TokensDeltaEvent)
    .registerEvent("ChatInferenceTrace", pb.InferenceTraceEvent)
    .registerEvent("ChatInferenceFinished", pb.InferenceFinishedEvent)
    .registerUIEvent("ChatMessageAccepted", pb.ChatMessageUpdate)
    .registerUIEvent("ChatAssistantStarted", pb.ChatMessageUpdate)
    .registerUIEvent("ChatAssistantDelta", pb.ChatMessageUpdate)
    .registerUIEvent("ChatAssistantFinished", pb.ChatMessageUpdate)
    .registerTimelineEntity("ChatMessage", pb.ChatMessageEntity)
}

function fakeAnswer(prompt) {
  return `Fake backend answer: you said "${prompt}". This response was generated by Goja JavaScript, carried through sessionstream projections, and delivered over a Go WebSocket handler mounted by Express.`
}

async function publishWithDelay(pub, name, payload, delayMs = 250) {
  await pub.publish(name, payload)
  await timer.sleep(delayMs)
}

async function publishTrace(pub, messageID, stage, detail, startedAt) {
  await publishWithDelay(pub, "ChatInferenceTrace", pb.InferenceTraceEvent.builder()
    .messageId(messageID)
    .stage(stage)
    .detail(detail)
    .elapsedMs(Date.now() - startedAt)
    .build(), 300)
}

function configureHub() {
  const schemas = registerSchemas()
  const h = ss.hub({ schemas })

  h.command("ChatStartInference", async (cmd, _session, pub) => {
    const prompt = String(cmd.payload.prompt || "")
    const userID = nextMessageId("user")
    const assistantID = nextMessageId("assistant")
    const answer = fakeAnswer(prompt)
    const startedAt = Date.now()
    const midpoint = Math.max(1, Math.floor(answer.length / 2))
    const chunks = [answer.slice(0, midpoint), answer.slice(midpoint)]

    await publishWithDelay(pub, "ChatUserMessageAccepted", pb.UserMessageAcceptedEvent.builder()
      .messageId(userID).role("user").content(prompt).streaming(false).build(), 200)

    await publishWithDelay(pub, "ChatInferenceStarted", pb.InferenceStartedEvent.builder()
      .messageId(assistantID).prompt(prompt).role("assistant").content("").status("streaming").streaming(true).build(), 350)

    await publishTrace(pub, assistantID, "planning", "Custom protobuf trace: planning a fake response", startedAt)

    let accumulated = ""
    for (const chunk of chunks) {
      accumulated += chunk
      await publishTrace(pub, assistantID, "chunk", `Custom protobuf trace: publishing ${chunk.length} characters`, startedAt)
      await publishWithDelay(pub, "ChatTokensDelta", pb.TokensDeltaEvent.builder()
        .messageId(assistantID).role("assistant").chunk(chunk).text(accumulated).content(accumulated).status("streaming").streaming(true).build(), 650)
    }

    await pub.publish("ChatInferenceFinished", pb.InferenceFinishedEvent.builder()
      .messageId(assistantID).role("assistant").text(answer).content(answer).status("done").streaming(false).build())
  })

  h.uiProjection((event) => {
    const p = event.payload
    if (event.name === "ChatUserMessageAccepted") {
      return [{ name: "ChatMessageAccepted", payload: pb.ChatMessageUpdate.builder()
        .messageId(p.messageId).role(p.role).content(p.content).status("done").streaming(false).build() }]
    }
    if (event.name === "ChatInferenceStarted") {
      return [{ name: "ChatAssistantStarted", payload: pb.ChatMessageUpdate.builder()
        .messageId(p.messageId).role(p.role).prompt(p.prompt).content("").status(p.status).streaming(true).build() }]
    }
    if (event.name === "ChatTokensDelta") {
      return [{ name: "ChatAssistantDelta", payload: pb.ChatMessageUpdate.builder()
        .messageId(p.messageId).role(p.role).chunk(p.chunk).text(p.text).content(p.content).status(p.status).streaming(true).build() }]
    }
    if (event.name === "ChatInferenceTrace") {
      return [{ name: "ChatAssistantDelta", payload: pb.ChatMessageUpdate.builder()
        .messageId(p.messageId).role("assistant").content(p.detail).status(`${p.stage} · ${p.elapsedMs}ms`).streaming(true).build() }]
    }
    if (event.name === "ChatInferenceFinished") {
      return [{ name: "ChatAssistantFinished", payload: pb.ChatMessageUpdate.builder()
        .messageId(p.messageId).role(p.role).text(p.text).content(p.content).status(p.status).streaming(false).build() }]
    }
    return []
  })

  h.timelineProjection((event, _session, view) => {
    const p = event.payload
    if (event.name === "ChatUserMessageAccepted") {
      return [{ kind: "ChatMessage", id: p.messageId, payload: pb.ChatMessageEntity.builder()
        .messageId(p.messageId).role(p.role).content(p.content).status("done").streaming(false).build() }]
    }
    if (event.name === "ChatInferenceStarted") {
      return [{ kind: "ChatMessage", id: p.messageId, payload: pb.ChatMessageEntity.builder()
        .messageId(p.messageId).role(p.role).content("").status(p.status).streaming(true).build() }]
    }
    if (event.name === "ChatInferenceTrace") {
      const current = view.get("ChatMessage", p.messageId)
      const currentPayload = (current && current.payload) || {}
      return [{ kind: "ChatMessage", id: p.messageId, payload: pb.ChatMessageEntity.builder()
        .messageId(p.messageId).role("assistant").text(currentPayload.text || currentPayload.content || p.detail).content(currentPayload.content || p.detail).status(`${p.stage} · ${p.elapsedMs}ms`).streaming(true).build() }]
    }
    if (event.name === "ChatTokensDelta" || event.name === "ChatInferenceFinished") {
      return [{ kind: "ChatMessage", id: p.messageId, payload: pb.ChatMessageEntity.builder()
        .messageId(p.messageId).role(p.role).text(p.text || p.content).content(p.content || p.text).status(p.status).streaming(Boolean(p.streaming)).build() }]
    }
    return []
  })

  return h
}


__verb__("serve", {
  name: "serve",
  output: "text",
  short: "Serve the xgoja sessionstream chatbot"
})
function serve() {
  const app = express.app()
  hub = configureHub()
  wsServer = ss.webSocket.server(hub)

  app.get("/", (_req, res) => res.type("text/html").send(assets.readFileSync("/app/public/index.html", "utf8")))
  app.staticFromAssetsModule("/assets", assets, "/app/public")
  app.get("/api/config", (_req, res) => res.json({ ok: true, defaultSessionId: sessionId }))
  app.get("/healthz", (_req, res) => res.json({ ok: true, app: "goja-chatdemo-server", connections: wsServer.connections().length }))
  app.post("/api/chat", async (req, res) => {
    const body = req.body || {}
    const sid = String(body.sessionId || sessionId)
    const prompt = String(body.prompt || "")
    if (!prompt) {
      res.status(400).json({ ok: false, error: "prompt is required" })
      return
    }
    await hub.submit(sid, "ChatStartInference", pb.StartInferenceCommand.builder().prompt(prompt).build())
    res.json({ ok: true, sessionId: sid, snapshot: hub.snapshot(sid) })
  })
  app.mount("/ws", wsServer)
}
