__package__({ name: "chatbot", short: "Sessionstream xgoja chatbot demo" })

const express = require("express")
const ss = require("sessionstream")
const pb = require("sessionstream.examples.chatdemo.v1")

const sessionId = "demo"
let messageSeq = 0
let hub = null
let wsServer = null

function nextMessageId(prefix) {
  messageSeq += 1
  return `${prefix}-${messageSeq}`
}

function registerSchemas() {
  return ss.schemas()
    .registerCommand("ChatStartInference", pb.StartInferenceCommand)
    .registerEvent("ChatUserMessageAccepted", pb.UserMessageAcceptedEvent)
    .registerEvent("ChatInferenceStarted", pb.InferenceStartedEvent)
    .registerEvent("ChatTokensDelta", pb.TokensDeltaEvent)
    .registerEvent("ChatInferenceFinished", pb.InferenceFinishedEvent)
    .registerUIEvent("ChatMessageAccepted", pb.ChatMessageUpdate)
    .registerUIEvent("ChatAssistantStarted", pb.ChatMessageUpdate)
    .registerUIEvent("ChatAssistantDelta", pb.ChatMessageUpdate)
    .registerUIEvent("ChatAssistantFinished", pb.ChatMessageUpdate)
    .registerTimelineEntity("ChatMessage", pb.ChatMessageEntity)
}

function fakeAnswer(prompt) {
  return `Fake backend answer: you said "${prompt}". This response was generated by Goja JavaScript, carried through sessionstream projections, and delivered over a Go WebSocket handler mounted by Express.`
}

function configureHub() {
  const schemas = registerSchemas()
  const h = ss.hub({ schemas })

  h.command("ChatStartInference", (cmd, _session, pub) => {
    const prompt = String(cmd.payload.prompt || "")
    const userID = nextMessageId("user")
    const assistantID = nextMessageId("assistant")
    const answer = fakeAnswer(prompt)
    const midpoint = Math.max(1, Math.floor(answer.length / 2))
    const chunks = [answer.slice(0, midpoint), answer.slice(midpoint)]

    pub.publish("ChatUserMessageAccepted", pb.UserMessageAcceptedEvent.builder()
      .messageId(userID).role("user").content(prompt).streaming(false).build())

    pub.publish("ChatInferenceStarted", pb.InferenceStartedEvent.builder()
      .messageId(assistantID).prompt(prompt).role("assistant").content("").status("streaming").streaming(true).build())

    let accumulated = ""
    for (const chunk of chunks) {
      accumulated += chunk
      pub.publish("ChatTokensDelta", pb.TokensDeltaEvent.builder()
        .messageId(assistantID).role("assistant").chunk(chunk).text(accumulated).content(accumulated).status("streaming").streaming(true).build())
    }

    pub.publish("ChatInferenceFinished", pb.InferenceFinishedEvent.builder()
      .messageId(assistantID).role("assistant").text(answer).content(answer).status("done").streaming(false).build())
  })

  h.uiProjection((event) => {
    const p = event.payload
    if (event.name === "ChatUserMessageAccepted") {
      return [{ name: "ChatMessageAccepted", payload: pb.ChatMessageUpdate.builder()
        .messageId(p.messageId).role(p.role).content(p.content).status("done").streaming(false).build() }]
    }
    if (event.name === "ChatInferenceStarted") {
      return [{ name: "ChatAssistantStarted", payload: pb.ChatMessageUpdate.builder()
        .messageId(p.messageId).role(p.role).prompt(p.prompt).content("").status(p.status).streaming(true).build() }]
    }
    if (event.name === "ChatTokensDelta") {
      return [{ name: "ChatAssistantDelta", payload: pb.ChatMessageUpdate.builder()
        .messageId(p.messageId).role(p.role).chunk(p.chunk).text(p.text).content(p.content).status(p.status).streaming(true).build() }]
    }
    if (event.name === "ChatInferenceFinished") {
      return [{ name: "ChatAssistantFinished", payload: pb.ChatMessageUpdate.builder()
        .messageId(p.messageId).role(p.role).text(p.text).content(p.content).status(p.status).streaming(false).build() }]
    }
    return []
  })

  h.timelineProjection((event, _session, view) => {
    const p = event.payload
    if (event.name === "ChatUserMessageAccepted") {
      return [{ kind: "ChatMessage", id: p.messageId, payload: pb.ChatMessageEntity.builder()
        .messageId(p.messageId).role(p.role).content(p.content).status("done").streaming(false).build() }]
    }
    if (event.name === "ChatInferenceStarted") {
      return [{ kind: "ChatMessage", id: p.messageId, payload: pb.ChatMessageEntity.builder()
        .messageId(p.messageId).role(p.role).content("").status(p.status).streaming(true).build() }]
    }
    if (event.name === "ChatTokensDelta" || event.name === "ChatInferenceFinished") {
      return [{ kind: "ChatMessage", id: p.messageId, payload: pb.ChatMessageEntity.builder()
        .messageId(p.messageId).role(p.role).text(p.text || p.content).content(p.content || p.text).status(p.status).streaming(Boolean(p.streaming)).build() }]
    }
    return []
  })

  return h
}

function html() {
  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>xgoja sessionstream chatbot</title>
  <style>
    body { font-family: sans-serif; max-width: 880px; margin: 2rem auto; background: #101318; color: #f4f7fb; }
    h1 { margin-bottom: .25rem; }
    .sub { color: #aab4c3; margin-bottom: 1rem; }
    #messages { border: 1px solid #303846; border-radius: 12px; min-height: 360px; padding: 1rem; background: #161b22; }
    .msg { margin: .65rem 0; padding: .65rem .8rem; border-radius: 10px; white-space: pre-wrap; }
    .user { background: #22395f; margin-left: 15%; }
    .assistant { background: #243727; margin-right: 15%; }
    .meta { color: #9aa6b2; font-size: .8rem; margin-bottom: .25rem; }
    form { display: flex; gap: .5rem; margin-top: 1rem; }
    input { flex: 1; padding: .75rem; border-radius: 8px; border: 1px solid #303846; background: #0d1117; color: #fff; }
    button { padding: .75rem 1rem; border-radius: 8px; border: 0; background: #4f8cff; color: white; font-weight: 700; }
    #status { color: #aab4c3; font-size: .9rem; margin-top: .75rem; }
  </style>
</head>
<body>
  <h1>xgoja sessionstream chatbot</h1>
  <div class="sub">All app logic is JavaScript. Go provides xgoja, protobuf builders, sessionstream, Express, and the WebSocket handler.</div>
  <div id="messages"></div>
  <form id="form">
    <input id="prompt" value="explain what is handling this request" autocomplete="off" />
    <button>Send</button>
  </form>
  <div id="status">connecting…</div>
<script>
const sessionId = "${sessionId}";
const messages = new Map();
const el = document.getElementById("messages");
const statusEl = document.getElementById("status");
function render() {
  el.innerHTML = "";
  for (const msg of messages.values()) {
    const div = document.createElement("div");
    div.className = "msg " + (msg.role === "user" ? "user" : "assistant");
    const meta = document.createElement("div");
    meta.className = "meta";
    meta.textContent = msg.role + " · " + msg.id + (msg.streaming ? " · streaming" : "");
    div.appendChild(meta);
    div.appendChild(document.createTextNode(msg.content || msg.text || ""));
    el.appendChild(div);
  }
  el.scrollTop = el.scrollHeight;
}
function payloadOf(frame) {
  const p = frame.payload || {};
  return p.value || p;
}
function upsertFromPayload(p) {
  if (!p || !p.messageId) return;
  messages.set(p.messageId, {
    id: p.messageId,
    role: p.role || "assistant",
    content: p.content || p.text || "",
    text: p.text || p.content || "",
    streaming: Boolean(p.streaming),
  });
  render();
}
const ws = new WebSocket("ws://" + location.host + "/ws");
ws.onopen = () => {
  statusEl.textContent = "websocket connected";
  ws.send(JSON.stringify({ subscribe: { sessionId, sinceSnapshotOrdinal: "0" } }));
};
ws.onmessage = (ev) => {
  const frame = JSON.parse(ev.data);
  if (frame.hello) statusEl.textContent = "connected as " + frame.hello.connectionId;
  if (frame.snapshot) {
    for (const ent of frame.snapshot.entities || []) upsertFromPayload(payloadOf(ent));
  }
  if (frame.uiEvent) upsertFromPayload(payloadOf(frame.uiEvent));
  if (frame.error) console.error(frame.error);
};
ws.onclose = () => { statusEl.textContent = "websocket closed"; };
document.getElementById("form").addEventListener("submit", async (e) => {
  e.preventDefault();
  const prompt = document.getElementById("prompt").value;
  await fetch("/api/chat", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ sessionId, prompt }) });
});
</script>
</body>
</html>`
}

__verb__("serve", {
  name: "serve",
  output: "text",
  short: "Serve the xgoja sessionstream chatbot"
})
function serve() {
  const app = express.app()
  hub = configureHub()
  wsServer = ss.webSocket.server(hub)

  app.get("/", (_req, res) => res.type("text/html").send(html()))
  app.get("/healthz", (_req, res) => res.json({ ok: true, app: "goja-chatdemo-server", connections: wsServer.connections().length }))
  app.post("/api/chat", (req, res) => {
    const body = req.body || {}
    const sid = String(body.sessionId || sessionId)
    const prompt = String(body.prompt || "")
    if (!prompt) {
      res.status(400).json({ ok: false, error: "prompt is required" })
      return
    }
    hub.submit(sid, "ChatStartInference", pb.StartInferenceCommand.builder().prompt(prompt).build())
    res.json({ ok: true, sessionId: sid, snapshot: hub.snapshot(sid) })
  })
  app.mount("/ws", wsServer)
}
