// Code generated by logcopter-gen; DO NOT EDIT.

package ws

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.sessionstream.pkg.sessionstream.transport.ws")
