// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/sessionstream/v1/transport.proto

package sessionstreamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*ClientFrame_Subscribe
	//	*ClientFrame_Unsubscribe
	//	*ClientFrame_Ping
	//	*ClientFrame_Pong
	Frame         isClientFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_proto_sessionstream_v1_transport_proto_rawDescGZIP(), []int{0}
}

func (x *ClientFrame) GetFrame() isClientFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *ClientFrame) GetSubscribe() *SubscribeRequest {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *ClientFrame) GetUnsubscribe() *UnsubscribeRequest {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Unsubscribe); ok {
			return x.Unsubscribe
		}
	}
	return nil
}

func (x *ClientFrame) GetPing() *PingFrame {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ClientFrame) GetPong() *PongFrame {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isClientFrame_Frame interface {
	isClientFrame_Frame()
}

type ClientFrame_Subscribe struct {
	Subscribe *SubscribeRequest `protobuf:"bytes,1,opt,name=subscribe,proto3,oneof"`
}

type ClientFrame_Unsubscribe struct {
	Unsubscribe *UnsubscribeRequest `protobuf:"bytes,2,opt,name=unsubscribe,proto3,oneof"`
}

type ClientFrame_Ping struct {
	Ping *PingFrame `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

type ClientFrame_Pong struct {
	Pong *PongFrame `protobuf:"bytes,4,opt,name=pong,proto3,oneof"`
}

func (*ClientFrame_Subscribe) isClientFrame_Frame() {}

func (*ClientFrame_Unsubscribe) isClientFrame_Frame() {}

func (*ClientFrame_Ping) isClientFrame_Frame() {}

func (*ClientFrame_Pong) isClientFrame_Frame() {}

type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*ServerFrame_Hello
	//	*ServerFrame_Snapshot
	//	*ServerFrame_Subscribed
	//	*ServerFrame_Unsubscribed
	//	*ServerFrame_UiEvent
	//	*ServerFrame_Error
	//	*ServerFrame_Ping
	//	*ServerFrame_Pong
	Frame         isServerFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_proto_sessionstream_v1_transport_proto_rawDescGZIP(), []int{1}
}

func (x *ServerFrame) GetFrame() isServerFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *ServerFrame) GetHello() *HelloFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ServerFrame) GetSnapshot() *SnapshotFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *ServerFrame) GetSubscribed() *SubscribedFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Subscribed); ok {
			return x.Subscribed
		}
	}
	return nil
}

func (x *ServerFrame) GetUnsubscribed() *UnsubscribedFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Unsubscribed); ok {
			return x.Unsubscribed
		}
	}
	return nil
}

func (x *ServerFrame) GetUiEvent() *UiEventFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_UiEvent); ok {
			return x.UiEvent
		}
	}
	return nil
}

func (x *ServerFrame) GetError() *ErrorFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerFrame) GetPing() *PingFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ServerFrame) GetPong() *PongFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isServerFrame_Frame interface {
	isServerFrame_Frame()
}

type ServerFrame_Hello struct {
	Hello *HelloFrame `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ServerFrame_Snapshot struct {
	Snapshot *SnapshotFrame `protobuf:"bytes,2,opt,name=snapshot,proto3,oneof"`
}

type ServerFrame_Subscribed struct {
	Subscribed *SubscribedFrame `protobuf:"bytes,3,opt,name=subscribed,proto3,oneof"`
}

type ServerFrame_Unsubscribed struct {
	Unsubscribed *UnsubscribedFrame `protobuf:"bytes,4,opt,name=unsubscribed,proto3,oneof"`
}

type ServerFrame_UiEvent struct {
	UiEvent *UiEventFrame `protobuf:"bytes,5,opt,name=ui_event,json=uiEvent,proto3,oneof"`
}

type ServerFrame_Error struct {
	Error *ErrorFrame `protobuf:"bytes,6,opt,name=error,proto3,oneof"`
}

type ServerFrame_Ping struct {
	Ping *PingFrame `protobuf:"bytes,7,opt,name=ping,proto3,oneof"`
}

type ServerFrame_Pong struct {
	Pong *PongFrame `protobuf:"bytes,8,opt,name=pong,proto3,oneof"`
}

func (*ServerFrame_Hello) isServerFrame_Frame() {}

func (*ServerFrame_Snapshot) isServerFrame_Frame() {}

func (*ServerFrame_Subscribed) isServerFrame_Frame() {}

func (*ServerFrame_Unsubscribed) isServerFrame_Frame() {}

func (*ServerFrame_UiEvent) isServerFrame_Frame() {}

func (*ServerFrame_Error) isServerFrame_Frame() {}

func (*ServerFrame_Ping) isServerFrame_Frame() {}

func (*ServerFrame_Pong) isServerFrame_Frame() {}

type HelloFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloFrame) Reset() {
	*x = HelloFrame{}
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloFrame) ProtoMessage() {}

func (x *HelloFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloFrame.ProtoReflect.Descriptor instead.
func (*HelloFrame) Descriptor() ([]byte, []int) {
	return file_proto_sessionstream_v1_transport_proto_rawDescGZIP(), []int{2}
}

func (x *HelloFrame) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type SubscribeRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SessionId            string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SinceSnapshotOrdinal uint64                 `protobuf:"varint,2,opt,name=since_snapshot_ordinal,json=sinceSnapshotOrdinal,proto3" json:"since_snapshot_ordinal,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_sessionstream_v1_transport_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubscribeRequest) GetSinceSnapshotOrdinal() uint64 {
	if x != nil {
		return x.SinceSnapshotOrdinal
	}
	return 0
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_sessionstream_v1_transport_proto_rawDescGZIP(), []int{4}
}

func (x *UnsubscribeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SubscribedFrame struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SessionId            string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SinceSnapshotOrdinal uint64                 `protobuf:"varint,2,opt,name=since_snapshot_ordinal,json=sinceSnapshotOrdinal,proto3" json:"since_snapshot_ordinal,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SubscribedFrame) Reset() {
	*x = SubscribedFrame{}
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribedFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribedFrame) ProtoMessage() {}

func (x *SubscribedFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribedFrame.ProtoReflect.Descriptor instead.
func (*SubscribedFrame) Descriptor() ([]byte, []int) {
	return file_proto_sessionstream_v1_transport_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribedFrame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubscribedFrame) GetSinceSnapshotOrdinal() uint64 {
	if x != nil {
		return x.SinceSnapshotOrdinal
	}
	return 0
}

type UnsubscribedFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribedFrame) Reset() {
	*x = UnsubscribedFrame{}
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribedFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribedFrame) ProtoMessage() {}

func (x *UnsubscribedFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribedFrame.ProtoReflect.Descriptor instead.
func (*UnsubscribedFrame) Descriptor() ([]byte, []int) {
	return file_proto_sessionstream_v1_transport_proto_rawDescGZIP(), []int{6}
}

func (x *UnsubscribedFrame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SnapshotFrame struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SnapshotOrdinal uint64                 `protobuf:"varint,2,opt,name=snapshot_ordinal,json=snapshotOrdinal,proto3" json:"snapshot_ordinal,omitempty"`
	Entities        []*SnapshotEntity      `protobuf:"bytes,3,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SnapshotFrame) Reset() {
	*x = SnapshotFrame{}
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotFrame) ProtoMessage() {}

func (x *SnapshotFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotFrame.ProtoReflect.Descriptor instead.
func (*SnapshotFrame) Descriptor() ([]byte, []int) {
	return file_proto_sessionstream_v1_transport_proto_rawDescGZIP(), []int{7}
}

func (x *SnapshotFrame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SnapshotFrame) GetSnapshotOrdinal() uint64 {
	if x != nil {
		return x.SnapshotOrdinal
	}
	return 0
}

func (x *SnapshotFrame) GetEntities() []*SnapshotEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type SnapshotEntity struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Kind             string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Id               string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedOrdinal   uint64                 `protobuf:"varint,3,opt,name=created_ordinal,json=createdOrdinal,proto3" json:"created_ordinal,omitempty"`
	LastEventOrdinal uint64                 `protobuf:"varint,4,opt,name=last_event_ordinal,json=lastEventOrdinal,proto3" json:"last_event_ordinal,omitempty"`
	Tombstone        bool                   `protobuf:"varint,5,opt,name=tombstone,proto3" json:"tombstone,omitempty"`
	Payload          *anypb.Any             `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SnapshotEntity) Reset() {
	*x = SnapshotEntity{}
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotEntity) ProtoMessage() {}

func (x *SnapshotEntity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotEntity.ProtoReflect.Descriptor instead.
func (*SnapshotEntity) Descriptor() ([]byte, []int) {
	return file_proto_sessionstream_v1_transport_proto_rawDescGZIP(), []int{8}
}

func (x *SnapshotEntity) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SnapshotEntity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SnapshotEntity) GetCreatedOrdinal() uint64 {
	if x != nil {
		return x.CreatedOrdinal
	}
	return 0
}

func (x *SnapshotEntity) GetLastEventOrdinal() uint64 {
	if x != nil {
		return x.LastEventOrdinal
	}
	return 0
}

func (x *SnapshotEntity) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

func (x *SnapshotEntity) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type UiEventFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EventOrdinal  uint64                 `protobuf:"varint,2,opt,name=event_ordinal,json=eventOrdinal,proto3" json:"event_ordinal,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UiEventFrame) Reset() {
	*x = UiEventFrame{}
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UiEventFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UiEventFrame) ProtoMessage() {}

func (x *UiEventFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UiEventFrame.ProtoReflect.Descriptor instead.
func (*UiEventFrame) Descriptor() ([]byte, []int) {
	return file_proto_sessionstream_v1_transport_proto_rawDescGZIP(), []int{9}
}

func (x *UiEventFrame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UiEventFrame) GetEventOrdinal() uint64 {
	if x != nil {
		return x.EventOrdinal
	}
	return 0
}

func (x *UiEventFrame) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UiEventFrame) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ErrorFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorFrame) Reset() {
	*x = ErrorFrame{}
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorFrame) ProtoMessage() {}

func (x *ErrorFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorFrame.ProtoReflect.Descriptor instead.
func (*ErrorFrame) Descriptor() ([]byte, []int) {
	return file_proto_sessionstream_v1_transport_proto_rawDescGZIP(), []int{10}
}

func (x *ErrorFrame) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorFrame) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorFrame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ErrorFrame) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type PingFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingFrame) Reset() {
	*x = PingFrame{}
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingFrame) ProtoMessage() {}

func (x *PingFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingFrame.ProtoReflect.Descriptor instead.
func (*PingFrame) Descriptor() ([]byte, []int) {
	return file_proto_sessionstream_v1_transport_proto_rawDescGZIP(), []int{11}
}

func (x *PingFrame) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type PongFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongFrame) Reset() {
	*x = PongFrame{}
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongFrame) ProtoMessage() {}

func (x *PongFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sessionstream_v1_transport_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongFrame.ProtoReflect.Descriptor instead.
func (*PongFrame) Descriptor() ([]byte, []int) {
	return file_proto_sessionstream_v1_transport_proto_rawDescGZIP(), []int{12}
}

func (x *PongFrame) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

var File_proto_sessionstream_v1_transport_proto protoreflect.FileDescriptor

const file_proto_sessionstream_v1_transport_proto_rawDesc = "" +
	"\n" +
	"&proto/sessionstream/v1/transport.proto\x12\x10sessionstream.v1\x1a\x19google/protobuf/any.proto\"\x8a\x02\n" +
	"\vClientFrame\x12B\n" +
	"\tsubscribe\x18\x01 \x01(\v2\".sessionstream.v1.SubscribeRequestH\x00R\tsubscribe\x12H\n" +
	"\vunsubscribe\x18\x02 \x01(\v2$.sessionstream.v1.UnsubscribeRequestH\x00R\vunsubscribe\x121\n" +
	"\x04ping\x18\x03 \x01(\v2\x1b.sessionstream.v1.PingFrameH\x00R\x04ping\x121\n" +
	"\x04pong\x18\x04 \x01(\v2\x1b.sessionstream.v1.PongFrameH\x00R\x04pongB\a\n" +
	"\x05frame\"\xf4\x03\n" +
	"\vServerFrame\x124\n" +
	"\x05hello\x18\x01 \x01(\v2\x1c.sessionstream.v1.HelloFrameH\x00R\x05hello\x12=\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x1f.sessionstream.v1.SnapshotFrameH\x00R\bsnapshot\x12C\n" +
	"\n" +
	"subscribed\x18\x03 \x01(\v2!.sessionstream.v1.SubscribedFrameH\x00R\n" +
	"subscribed\x12I\n" +
	"\funsubscribed\x18\x04 \x01(\v2#.sessionstream.v1.UnsubscribedFrameH\x00R\funsubscribed\x12;\n" +
	"\bui_event\x18\x05 \x01(\v2\x1e.sessionstream.v1.UiEventFrameH\x00R\auiEvent\x124\n" +
	"\x05error\x18\x06 \x01(\v2\x1c.sessionstream.v1.ErrorFrameH\x00R\x05error\x121\n" +
	"\x04ping\x18\a \x01(\v2\x1b.sessionstream.v1.PingFrameH\x00R\x04ping\x121\n" +
	"\x04pong\x18\b \x01(\v2\x1b.sessionstream.v1.PongFrameH\x00R\x04pongB\a\n" +
	"\x05frame\"1\n" +
	"\n" +
	"HelloFrame\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"g\n" +
	"\x10SubscribeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x124\n" +
	"\x16since_snapshot_ordinal\x18\x02 \x01(\x04R\x14sinceSnapshotOrdinal\"3\n" +
	"\x12UnsubscribeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"f\n" +
	"\x0fSubscribedFrame\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x124\n" +
	"\x16since_snapshot_ordinal\x18\x02 \x01(\x04R\x14sinceSnapshotOrdinal\"2\n" +
	"\x11UnsubscribedFrame\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x97\x01\n" +
	"\rSnapshotFrame\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12)\n" +
	"\x10snapshot_ordinal\x18\x02 \x01(\x04R\x0fsnapshotOrdinal\x12<\n" +
	"\bentities\x18\x03 \x03(\v2 .sessionstream.v1.SnapshotEntityR\bentities\"\xd9\x01\n" +
	"\x0eSnapshotEntity\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12'\n" +
	"\x0fcreated_ordinal\x18\x03 \x01(\x04R\x0ecreatedOrdinal\x12,\n" +
	"\x12last_event_ordinal\x18\x04 \x01(\x04R\x10lastEventOrdinal\x12\x1c\n" +
	"\ttombstone\x18\x05 \x01(\bR\ttombstone\x12.\n" +
	"\apayload\x18\x06 \x01(\v2\x14.google.protobuf.AnyR\apayload\"\x96\x01\n" +
	"\fUiEventFrame\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\revent_ordinal\x18\x02 \x01(\x04R\feventOrdinal\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12.\n" +
	"\apayload\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\apayload\"q\n" +
	"\n" +
	"ErrorFrame\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\"!\n" +
	"\tPingFrame\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\"!\n" +
	"\tPongFrame\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonceB]Z[github.com/go-go-golems/sessionstream/pkg/sessionstream/pb/sessionstream/v1;sessionstreamv1b\x06proto3"

var (
	file_proto_sessionstream_v1_transport_proto_rawDescOnce sync.Once
	file_proto_sessionstream_v1_transport_proto_rawDescData []byte
)

func file_proto_sessionstream_v1_transport_proto_rawDescGZIP() []byte {
	file_proto_sessionstream_v1_transport_proto_rawDescOnce.Do(func() {
		file_proto_sessionstream_v1_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sessionstream_v1_transport_proto_rawDesc), len(file_proto_sessionstream_v1_transport_proto_rawDesc)))
	})
	return file_proto_sessionstream_v1_transport_proto_rawDescData
}

var file_proto_sessionstream_v1_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_sessionstream_v1_transport_proto_goTypes = []any{
	(*ClientFrame)(nil),        // 0: sessionstream.v1.ClientFrame
	(*ServerFrame)(nil),        // 1: sessionstream.v1.ServerFrame
	(*HelloFrame)(nil),         // 2: sessionstream.v1.HelloFrame
	(*SubscribeRequest)(nil),   // 3: sessionstream.v1.SubscribeRequest
	(*UnsubscribeRequest)(nil), // 4: sessionstream.v1.UnsubscribeRequest
	(*SubscribedFrame)(nil),    // 5: sessionstream.v1.SubscribedFrame
	(*UnsubscribedFrame)(nil),  // 6: sessionstream.v1.UnsubscribedFrame
	(*SnapshotFrame)(nil),      // 7: sessionstream.v1.SnapshotFrame
	(*SnapshotEntity)(nil),     // 8: sessionstream.v1.SnapshotEntity
	(*UiEventFrame)(nil),       // 9: sessionstream.v1.UiEventFrame
	(*ErrorFrame)(nil),         // 10: sessionstream.v1.ErrorFrame
	(*PingFrame)(nil),          // 11: sessionstream.v1.PingFrame
	(*PongFrame)(nil),          // 12: sessionstream.v1.PongFrame
	(*anypb.Any)(nil),          // 13: google.protobuf.Any
}
var file_proto_sessionstream_v1_transport_proto_depIdxs = []int32{
	3,  // 0: sessionstream.v1.ClientFrame.subscribe:type_name -> sessionstream.v1.SubscribeRequest
	4,  // 1: sessionstream.v1.ClientFrame.unsubscribe:type_name -> sessionstream.v1.UnsubscribeRequest
	11, // 2: sessionstream.v1.ClientFrame.ping:type_name -> sessionstream.v1.PingFrame
	12, // 3: sessionstream.v1.ClientFrame.pong:type_name -> sessionstream.v1.PongFrame
	2,  // 4: sessionstream.v1.ServerFrame.hello:type_name -> sessionstream.v1.HelloFrame
	7,  // 5: sessionstream.v1.ServerFrame.snapshot:type_name -> sessionstream.v1.SnapshotFrame
	5,  // 6: sessionstream.v1.ServerFrame.subscribed:type_name -> sessionstream.v1.SubscribedFrame
	6,  // 7: sessionstream.v1.ServerFrame.unsubscribed:type_name -> sessionstream.v1.UnsubscribedFrame
	9,  // 8: sessionstream.v1.ServerFrame.ui_event:type_name -> sessionstream.v1.UiEventFrame
	10, // 9: sessionstream.v1.ServerFrame.error:type_name -> sessionstream.v1.ErrorFrame
	11, // 10: sessionstream.v1.ServerFrame.ping:type_name -> sessionstream.v1.PingFrame
	12, // 11: sessionstream.v1.ServerFrame.pong:type_name -> sessionstream.v1.PongFrame
	8,  // 12: sessionstream.v1.SnapshotFrame.entities:type_name -> sessionstream.v1.SnapshotEntity
	13, // 13: sessionstream.v1.SnapshotEntity.payload:type_name -> google.protobuf.Any
	13, // 14: sessionstream.v1.UiEventFrame.payload:type_name -> google.protobuf.Any
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_sessionstream_v1_transport_proto_init() }
func file_proto_sessionstream_v1_transport_proto_init() {
	if File_proto_sessionstream_v1_transport_proto != nil {
		return
	}
	file_proto_sessionstream_v1_transport_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientFrame_Subscribe)(nil),
		(*ClientFrame_Unsubscribe)(nil),
		(*ClientFrame_Ping)(nil),
		(*ClientFrame_Pong)(nil),
	}
	file_proto_sessionstream_v1_transport_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerFrame_Hello)(nil),
		(*ServerFrame_Snapshot)(nil),
		(*ServerFrame_Subscribed)(nil),
		(*ServerFrame_Unsubscribed)(nil),
		(*ServerFrame_UiEvent)(nil),
		(*ServerFrame_Error)(nil),
		(*ServerFrame_Ping)(nil),
		(*ServerFrame_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sessionstream_v1_transport_proto_rawDesc), len(file_proto_sessionstream_v1_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sessionstream_v1_transport_proto_goTypes,
		DependencyIndexes: file_proto_sessionstream_v1_transport_proto_depIdxs,
		MessageInfos:      file_proto_sessionstream_v1_transport_proto_msgTypes,
	}.Build()
	File_proto_sessionstream_v1_transport_proto = out.File
	file_proto_sessionstream_v1_transport_proto_goTypes = nil
	file_proto_sessionstream_v1_transport_proto_depIdxs = nil
}
