// Code generated by logcopter-gen; DO NOT EDIT.

package provider

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.sessionstream.pkg.js.modules.chatdemo.provider")
