// Code generated by xgoja; DO NOT EDIT.
package xgojaruntime

import (
	"context"
	"embed"
	"encoding/json"
	"fmt"
	"io"

	"github.com/dop251/goja_nodejs/require"
	"github.com/go-go-golems/glazed/pkg/cli"
	"github.com/go-go-golems/glazed/pkg/cmds/values"
	"github.com/go-go-golems/go-go-goja/pkg/engine"
	"github.com/go-go-golems/go-go-goja/pkg/xgoja/app"
	"github.com/go-go-golems/go-go-goja/pkg/xgoja/dtsgen"
	"github.com/go-go-golems/go-go-goja/pkg/xgoja/providerapi"
	go_go_goja_core "github.com/go-go-golems/go-go-goja/pkg/xgoja/providers/core"
	go_go_goja_host "github.com/go-go-golems/go-go-goja/pkg/xgoja/providers/host"
	go_go_goja_http "github.com/go-go-golems/go-go-goja/pkg/xgoja/providers/http"
	sessionstream_chatdemo "github.com/go-go-golems/sessionstream/pkg/js/modules/chatdemo/provider"
	sessionstream "github.com/go-go-golems/sessionstream/pkg/js/modules/sessionstream/provider"
	"github.com/spf13/cobra"
)

const EmbeddedRuntimePlanJSON = `{
  "schema": "xgoja/runtime/v2",
  "name": "goja-redis-chatdemo-server",
  "app": {
    "name": "goja-redis-chatdemo-server"
  },
  "target": {
    "kind": "package",
    "output": "internal/xgojaruntime"
  },
  "providers": [
    {
      "id": "go-go-goja-host"
    },
    {
      "id": "go-go-goja-http"
    },
    {
      "id": "go-go-goja-core"
    },
    {
      "id": "sessionstream"
    },
    {
      "id": "sessionstream-chatdemo"
    }
  ],
  "runtime": {
    "modules": [
      {
        "provider": "go-go-goja-host",
        "name": "fs",
        "as": "fs:assets",
        "config": {
          "embedded": {
            "allow": true,
            "mounts": [
              {
                "asset": "app-assets",
                "mount": "/app"
              }
            ]
          }
        }
      },
      {
        "provider": "go-go-goja-http",
        "name": "express",
        "as": "express"
      },
      {
        "provider": "go-go-goja-core",
        "name": "timer",
        "as": "timer"
      },
      {
        "provider": "sessionstream",
        "name": "sessionstream",
        "as": "sessionstream"
      },
      {
        "provider": "sessionstream-chatdemo",
        "name": "sessionstream.examples.chatdemo.v1",
        "as": "sessionstream.examples.chatdemo.v1"
      }
    ]
  },
  "sources": [
    {
      "id": "sites",
      "kind": "jsverbs",
      "path": "xgoja_embed/jsverbs/sites",
      "embed": true
    },
    {
      "id": "redis-tools",
      "kind": "jsverbs",
      "path": "xgoja_embed/jsverbs/redis_tools",
      "embed": true
    },
    {
      "id": "app-assets",
      "kind": "assets",
      "path": "xgoja_embed/assets/app_assets",
      "embed": true
    }
  ],
  "commands": [
    {
      "id": "verbs",
      "type": "builtin.jsverbs",
      "name": "verbs",
      "sources": [
        "sites",
        "redis-tools"
      ]
    },
    {
      "id": "serve",
      "type": "provider.command-set",
      "name": "serve",
      "mount": "serve",
      "provider": "go-go-goja-http",
      "sources": [
        "sites"
      ]
    }
  ],
  "artifacts": [
    {
      "id": "runtime",
      "type": "runtime-package",
      "output": "internal/xgojaruntime",
      "package": "xgojaruntime",
      "sources": [
        "sites",
        "redis-tools"
      ]
    },
    {
      "id": "embedded-assets",
      "type": "embedded-assets",
      "sources": [
        "app-assets"
      ]
    }
  ]
}
`

//go:embed xgoja_embed/jsverbs/*
var embeddedJSVerbs embed.FS

//go:embed all:xgoja_embed/assets/*
var embeddedAssets embed.FS

type Options struct {
	Out               io.Writer
	MiddlewaresFunc   cli.CobraMiddlewaresFunc
	ConfigureServices func(*app.HostServices)
}

type Bundle struct {
	Providers   *providerapi.ProviderRegistry
	RuntimePlan *app.RuntimePlan
	Host        *app.Host
}

func RegisterProviders(registry *providerapi.ProviderRegistry) error {
	if registry == nil {
		return fmt.Errorf("provider registry is nil")
	}
	if err := go_go_goja_host.Register(registry); err != nil {
		return err
	}
	if err := go_go_goja_http.Register(registry); err != nil {
		return err
	}
	if err := go_go_goja_core.Register(registry); err != nil {
		return err
	}
	if err := sessionstream.Register(registry); err != nil {
		return err
	}
	if err := sessionstream_chatdemo.Register(registry); err != nil {
		return err
	}
	return nil
}

func DecodeRuntimePlan() (*app.RuntimePlan, error) {
	runtimePlan := &app.RuntimePlan{}
	if err := json.Unmarshal([]byte(EmbeddedRuntimePlanJSON), runtimePlan); err != nil {
		return nil, err
	}
	return runtimePlan, nil
}

func NewBundle(opts Options) (*Bundle, error) {
	registry := providerapi.NewProviderRegistry()
	if err := RegisterProviders(registry); err != nil {
		return nil, err
	}
	runtimePlan, err := DecodeRuntimePlan()
	if err != nil {
		return nil, err
	}
	host := app.NewHostWithOptions(registry, runtimePlan, app.HostOptions{
		EmbeddedJSVerbs:   embeddedJSVerbs,
		EmbeddedAssets:    embeddedAssets,
		Out:               opts.Out,
		MiddlewaresFunc:   opts.MiddlewaresFunc,
		ConfigureServices: opts.ConfigureServices,
	})
	return &Bundle{Providers: registry, RuntimePlan: runtimePlan, Host: host}, nil
}

func (b *Bundle) TypeScriptDeclarations() (string, error) {
	if b == nil || b.Host == nil {
		return "", fmt.Errorf("xgoja runtime bundle is not initialized")
	}
	result, err := b.Host.TypeScriptDeclarations(dtsgen.Options{})
	if err != nil {
		return "", err
	}
	return result.DTS, nil
}

func (b *Bundle) WriteTypeScriptDeclarations(w io.Writer) error {
	if b == nil || b.Host == nil {
		return fmt.Errorf("xgoja runtime bundle is not initialized")
	}
	return b.Host.WriteTypeScriptDeclarations(w, dtsgen.Options{})
}

func (b *Bundle) NewRuntime(ctx context.Context, opts ...require.Option) (*engine.Runtime, error) {
	if b == nil || b.Host == nil || b.Host.Factory == nil {
		return nil, fmt.Errorf("xgoja runtime bundle is not initialized")
	}
	return b.Host.Factory.NewRuntime(ctx, opts...)
}

func (b *Bundle) NewRuntimeFromSections(ctx context.Context, vals *values.Values, opts ...require.Option) (*engine.Runtime, error) {
	if b == nil || b.Host == nil || b.Host.Factory == nil {
		return nil, fmt.Errorf("xgoja runtime bundle is not initialized")
	}
	return b.Host.Factory.NewRuntimeFromSections(ctx, vals, opts...)
}

func (b *Bundle) AttachDefaultCommands(root *cobra.Command) {
	if b == nil || b.Host == nil {
		return
	}
	b.Host.AttachDefaultCommands(root)
}
